// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_pro_gamer = "CgkIsL2Cj_oUEAIQFA"; // <GPGSID>
        public const string achievement_extra_lives = "CgkIsL2Cj_oUEAIQFw"; // <GPGSID>
        public const string achievement_its_the_power_of_love = "CgkIsL2Cj_oUEAIQGw"; // <GPGSID>
        public const string achievement_one_with_nature = "CgkIsL2Cj_oUEAIQFg"; // <GPGSID>
        public const string achievement_sanctuary = "CgkIsL2Cj_oUEAIQDA"; // <GPGSID>
        public const string leaderboard_endless_game = "CgkIsL2Cj_oUEAIQAg"; // <GPGSID>
        public const string achievement_thats_impressive = "CgkIsL2Cj_oUEAIQHw"; // <GPGSID>
        public const string achievement_more = "CgkIsL2Cj_oUEAIQEg"; // <GPGSID>
        public const string achievement_bring_it_on = "CgkIsL2Cj_oUEAIQDQ"; // <GPGSID>
        public const string achievement_ive_got_this = "CgkIsL2Cj_oUEAIQDg"; // <GPGSID>
        public const string achievement_barber_jewler = "CgkIsL2Cj_oUEAIQFQ"; // <GPGSID>
        public const string achievement_pigeon_lady = "CgkIsL2Cj_oUEAIQCg"; // <GPGSID>
        public const string achievement_rookie_numbers = "CgkIsL2Cj_oUEAIQEQ"; // <GPGSID>
        public const string achievement_jewel_crusher = "CgkIsL2Cj_oUEAIQDw"; // <GPGSID>
        public const string leaderboard_top_scores = "CgkIsL2Cj_oUEAIQAw"; // <GPGSID>
        public const string achievement_i_love_it = "CgkIsL2Cj_oUEAIQEw"; // <GPGSID>
        public const string achievement_amateur = "CgkIsL2Cj_oUEAIQBQ"; // <GPGSID>
        public const string achievement_the_other_way_arround = "CgkIsL2Cj_oUEAIQGQ"; // <GPGSID>
        public const string achievement_and_so_it_begins = "CgkIsL2Cj_oUEAIQBA"; // <GPGSID>
        public const string achievement_nice = "CgkIsL2Cj_oUEAIQHQ"; // <GPGSID>
        public const string achievement_angry_birds = "CgkIsL2Cj_oUEAIQCQ"; // <GPGSID>
        public const string achievement_unstoppable = "CgkIsL2Cj_oUEAIQEA"; // <GPGSID>
        public const string achievement_truly_epic = "CgkIsL2Cj_oUEAIQIA"; // <GPGSID>
        public const string achievement_good_run = "CgkIsL2Cj_oUEAIQHg"; // <GPGSID>
        public const string achievement_the_game = "CgkIsL2Cj_oUEAIQIQ"; // <GPGSID>
        public const string achievement_millonare = "CgkIsL2Cj_oUEAIQBw"; // <GPGSID>
        public const string achievement_gotta_catch_em_all = "CgkIsL2Cj_oUEAIQCw"; // <GPGSID>
        public const string achievement_jewel_collector = "CgkIsL2Cj_oUEAIQBg"; // <GPGSID>
        public const string achievement_its_a_kind_of_magic = "CgkIsL2Cj_oUEAIQGg"; // <GPGSID>
        public const string achievement_quiet_please = "CgkIsL2Cj_oUEAIQGA"; // <GPGSID>
        public const string achievement_someone_wants_a_challenge = "CgkIsL2Cj_oUEAIQHA"; // <GPGSID>
        public const string achievement_royalty = "CgkIsL2Cj_oUEAIQCA"; // <GPGSID>

}

